project_id = "iacjtvvlyxkmrzaxkedk"

[functions.quran-search]
verify_jwt = false

[functions.update-arabic-verses]
verify_jwt = true

[functions.import-verses]
verify_jwt = true

[functions.import-duas]
verify_jwt = true

[functions.fetch-bengali-tafsir]
verify_jwt = true

[functions.generate-tafsir]
verify_jwt = true

[functions.elevenlabs-tts]
verify_jwt = false

[functions.import-tafsir]
verify_jwt = true

[functions.import-hadiths]
verify_jwt = true

[functions.import-bengali-hadiths]
verify_jwt = true
