project_id = "iacjtvvlyxkmrzaxkedk"

[functions.quran-search]
verify_jwt = false

[functions.update-arabic-verses]
verify_jwt = false

[functions.import-verses]
verify_jwt = false

[functions.import-duas]
verify_jwt = false

[functions.fetch-bengali-tafsir]
verify_jwt = false

[functions.generate-tafsir]
verify_jwt = false
