project_id = "iacjtvvlyxkmrzaxkedk"

[functions.quran-search]
verify_jwt = false

[functions.update-arabic-verses]
verify_jwt = false

[functions.import-verses]
verify_jwt = false

[functions.import-duas]
verify_jwt = false

[functions.fetch-bengali-tafsir]
verify_jwt = false

[functions.generate-tafsir]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.import-tafsir]
verify_jwt = false

[functions.import-hadiths]
verify_jwt = false

[functions.import-bengali-hadiths]
verify_jwt = false

[functions.import-hadiths-v2]
verify_jwt = false

[functions.hadith-ai-search]
verify_jwt = false

[functions.rate-limited-auth]
verify_jwt = false
